name: checkout
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        run: |
          git clone https://github.com/Softwaresingham/SS_GITHUB_ACTIONS.git
          cd SS_GITHUB_ACTIONS
          ls -lrt
