name: java-install
on: 
  push
jobs:
  java:
    runs-on: ubuntu-latest
    steps: 
      - name: install
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
      -name: verify
       run: java -version
